### ISSUE TITLE
is there any chance to make turbo work without luajit-ffi?

### ISSUE THREAD

**Issue by Nossiac** [kernelsauce/turbo#187]
I do like the tornado framework, especially the template part, simple and powerful.
I don't care about performance, since my target platform is resource-limited embedded device and it doesn't have heavy web traffic.

Based on those, I found turbo here.
But the problem is, luajit-ffi only works on several platforms, mine not included.
if there's a chance to make turbo work without luajit-ffi, i would like have a try.

**Comment by kernelsauce** [comment]
Its possible, less now that we already support using LuaSocket. To make it possible you would have to make a HTTP parser in plain Lua, since the current one is in C and called via FFI. You would also have to write a Lua buffer class, since the current one is based on FFI for speed. There are still some parts of the project that would not really work that are based on direct C calls. But of course everything is possible. Though its not on the list of things to do at the moment to be honest.
